version: '2.4'

services:
  web:
    command: python /app/manage.py runserver 0.0.0.0:3334
    entrypoint: ""
    environment:
      DEBUG: ${DEBUG:-True}
    # Bind mount project to PyCharm remote debugger's default working directory
    volumes:
      - ./backend:/opt/project/backend